# Generated by Django 5.1 on 2025-12-14 17:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('running', 'Running'), ('cycling', 'Cycling'), ('walking', 'Walking'), ('swimming', 'Swimming'), ('hiking', 'Hiking'), ('yoga', 'Yoga'), ('gym', 'Gym Workout'), ('crossfit', 'CrossFit'), ('other', 'Other')], default='other', max_length=50)),
                ('duration_sec', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('distance_m', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('elevation_gain_m', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('ele', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cadence', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='activities.activity')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='activities.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('height_cm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_distance_m', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_duration_sec', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('duration_sec__gte', 0)), name='activity_duration_sec_positive'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('distance_m__gte', 0)), name='activity_distance_m_positive'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('elevation_gain_m__gte', 0)), name='activity_elevation_gain_m_positive'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gte', models.F('start_time'))), name='activity_end_time_gte_start_time'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('activity_type__in', ['running', 'cycling', 'walking', 'swimming', 'hiking', 'yoga', 'gym', 'crossfit', 'other'])), name='activity_type_valid_choice'),
        ),
        migrations.AddConstraint(
            model_name='activitypoint',
            constraint=models.CheckConstraint(condition=models.Q(('speed__gte', 0)), name='activitypoint_speed_positive'),
        ),
        migrations.AddConstraint(
            model_name='activitypoint',
            constraint=models.CheckConstraint(condition=models.Q(('cadence__gte', 0)), name='activitypoint_cadence_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('follower', 'followee')},
        ),
        migrations.AlterUniqueTogether(
            name='kudos',
            unique_together={('activity', 'user')},
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('weight_kg__gte', 0)), name='profile_weight_kg_positive'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('height_cm__gte', 0)), name='profile_height_cm_positive'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 0)), name='profile_age_positive'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('gender__in', ['male', 'female', 'other']), ('gender__isnull', True), _connector='OR'), name='profile_gender_valid_choice'),
        ),
        migrations.AddConstraint(
            model_name='usermonthlystats',
            constraint=models.CheckConstraint(condition=models.Q(('total_distance_m__gte', 0)), name='stats_distance_m_positive'),
        ),
        migrations.AddConstraint(
            model_name='usermonthlystats',
            constraint=models.CheckConstraint(condition=models.Q(('total_duration_sec__gte', 0)), name='stats_duration_sec_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='usermonthlystats',
            unique_together={('user', 'year', 'month')},
        ),
    ]
